"""empty message

Revision ID: b5f547033381
Revises: 3c26cf2ea2f5
Create Date: 2025-01-30 22:08:51.647381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5f547033381'
down_revision = '3c26cf2ea2f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_Url', sa.String(length=10000), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('image_Url')

    # ### end Alembic commands ###
